### ISSUE TITLE
Если в списке нет городов, то при добавлении нового приложение падает 

### ISSUE THREAD

**Issue by DmitryLaenko** [VESNNA/TestWorkWeatherApp#2]
DispatchQueue.global(qos: .userInteractive).sync {
                        
                        let newCity = Cities(name: currentWeather.city, country: currentWeather.country, id: currentWeather.id)
                        
                        StorageManager.saveObject(newCity)
                        **self.citiesList.insert(newCity, at: 1)**
                    }

**Comment by VESNNA** [comment]
решение: использовать тернарный оператор для проверки на выход за диапазон значений массива citiesList
`self.citiesList.isEmpty ? self.citiesList.insert(newCity, at: 0) : self.citiesList.insert(newCity, at: 1)`
